### ISSUE TITLE
Why do I get a lot of messages after I publish a message

### ISSUE THREAD

**Issue by protectedMan** [hannesa2/paho.mqtt.android#176]

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/125224343-09de4980-e300-11eb-8f35-4320eb1bbf6a.png)

**Comment by hannesa2** [comment]
Indeed, there are more such "miracles", eg Qos and AlarmPing doesn't work like expected.
I observed it in (non-maintained) upstream repo, that's why I started to modernize it and maintain it. A repo in this state would be a full time job, and to cry doesn't help, only _to do_ makes sense.
Everyone is warmly welcome to help with this

**Comment by protectedMan** [comment]
https://github.com/hannesa2/paho.mqtt.android/pull/177
