### ISSUE TITLE
publish returns a token with messageId = 0

### ISSUE THREAD

**Issue by LucaBL** [hannesa2/paho.mqtt.android#370]
Hello, here is my problem:
In case there's currently no connection, if I call publish, it returns a token with no message id (0).
After this, when the connection returns, the previous message gets correctly delivered, and I receive a deliveryComplete callback with a token containing the correct messageId, but since I didn't receive the correct one during publish, I have no means to compare them and recognize the message that was just delivered.

I noticed that in the function

```
MqttAndroidClient.kt

override fun publish(topic: String, payload: ByteArray, qos: Int, retained: Boolean, userContext: Any?, callback: IMqttActionListener?): IMqttDeliveryToken {
```

the variable `activityToken` always contains what I need, but 'token', the value returned in the end, doesn't contain that in this particular case.

Am I doing something wrong? I thought publish would return the correct messageId no matter the current connection status.
Thank you

**Comment by hannesa2** [comment]
I didn't invented the logic. It's from old non-maintained eclipse repository.

It has to deliver back an `IMqttDeliveryToken` because it extends from
`public interface IMqttAsyncClient extends AutoCloseable {`

Any suggestion ? I'm not sure how to improve it. Btw, having there 3 tokens can always confuse 
If you find some improvement, please make a pull request.

**Comment by LucaBL** [comment]
No worries, I was just trying to understand if it was me or a bug. If I come up with what seems a solution I'll let you know, thanks!

**Comment by hannesa2** [comment]
Ok, in the meantime I close it. Please feel free to reopen it again
