### ISSUE TITLE
Exact alarm

### ISSUE THREAD

**Issue by wwqbus** [hannesa2/paho.mqtt.android#567]
in the 3.6.1 there is the use of an exact timer for the ping but it looks like its not checking if it has permission to use this 

can i pull to fix it?

Your use of exact alarms is causing your app to crash for some Android users
Your app schedules exact alarms without checking whether the SCHEDULE_EXACT_ALARM permission has been granted. This is causing your app to crash for users on Android 14 because the permission is no longer granted by default.

In most cases, alternative methods of scheduling work or inexact alarms are more appropriate. If your use of exact alarms is justified, update your app so that it checks this permission is granted before scheduling.

**Comment by hannesa2** [comment]
> can i pull to fix it?

sure !

**Comment by ramses-i** [comment]
Hello, 

Any updates on this? 

Google is rejecting new updates on Google Play Console because of the use of USE_EXACT_ALARM.  

[It sends me to this article](https://support.google.com/googleplay/android-developer/answer/9888170#exact_alarm)

I am not using USE_EXACT_ALARM on my app directly, I looked for it and the only lib that currently uses it on my project is this one. 

I do use SCHEDULE_EXACT_ALARM for local notifications, but I have make the changes on my code to manage this permission.

I also noticed that it crashes the app on Android 14 when trying to use:
`info.mqtt.android.service.ping.AlarmPingSender.schedule (AlarmPingSender.kt:86) `

It throws: 
`Fatal Exception: java.lang.SecurityException
Caller {app_package_id} needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.`

I guess for the same reason stated from @wwqbus that is not checking if it has permission before doing it.

**Comment by hannesa2** [comment]
please use https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.2

**Comment by wwqbus** [comment]
i added a pull request so that it doesn't scheduele with exact if it isn't allowed

**Comment by hannesa2** [comment]
I guess it's solved by #568
